analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - "*/.g.dart"
    - "*/.freezed.dart"

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Estilo de código
    prefer_single_quotes: true
    always_use_package_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    omit_local_variable_types: false

    # Null safety & segurança
    avoid_null_checks_in_equality_operators: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true

    # Código mais limpo
    avoid_empty_else: true
    avoid_positional_boolean_parameters: true
    unnecessary_this: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    unnecessary_const: true
    unnecessary_new: true

    # Boas práticas em collections
    prefer_collection_literals: true
    unnecessary_lambdas: true

    # Async
    unawaited_futures: true

    # Readability
    use_super_parameters: true
    prefer_expression_function_bodies: true
    avoid_classes_with_only_static_members: true

    # Safety
    no_leading_underscores_for_local_identifiers: true